[package]
name = "hyperchain_da"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
celestia-rpc = {git="https://github.com/eigerco/lumina.git", rev="8094d04b76e3f3c08667d654c8b6b5bb3fdeab33"}
celestia-types = {git="https://github.com/eigerco/lumina.git", rev="8094d04b76e3f3c08667d654c8b6b5bb3fdeab33"}
ssz_rs = "0.9.0"
bincode = "1.3.3"
hex = "0.4.3"
nmt-rs = {git="https://github.com/Sovereign-Labs/nmt-rs.git", rev="ac03d7c"}
alloy-core = "0.7.6"
alloy-sol-types = "0.7.6"
alloy-sol-macro = "0.7.6"

[dev-dependencies]
serde_json = "1.0.114"

[patch.crates-io]
nmt-rs = {git="https://github.com/Sovereign-Labs/nmt-rs.git", rev="ac03d7c"}