[package]
name = "hyperchain_da"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
celestia-rpc = "0.2.0"
celestia-types = "0.2.0"
ssz_rs = "0.9.0"
bincode = "1.3.3"
hex = "0.4.3"